import com.google.protobuf.CodedInputStream;
import com.google.protobuf.CodedOutputStream;
import com.google.protobuf.Message;
import common.ConstantUtil;
import common.SeqGenerator;
import model.Truck;
import service.TruckService;
import common.BuilderUtil;
import messaging.WorldClient;
import org.apache.ibatis.session.SqlSession;
import common.MyBatisUtil;
import protocol.WorldUps;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AppUser {
//    public static void main(String[] args) throws InterruptedException, IOException {
//        String host = "127.0.0.1";
//        int port = 12345;
//        int maxRetries = 60;
//        int retryInterval = 5000; // 等待间隔为 5 秒
//        boolean databaseStarted = false;
//        System.out.println("Waiting for PostgreSQL database to start...");
//        while (maxRetries > 0 && !databaseStarted) {
//            try {
//                SqlSession sqlSession = MyBatisUtil.getSqlSession();
//                sqlSession.close();
//                databaseStarted = true;
//            } catch (Exception e) {
//                System.out.println("PostgreSQL database is not yet ready, retrying in " + retryInterval / 1000 + " seconds...");
//                Thread.sleep(retryInterval);
//                maxRetries--;
//            }
//        }
//        if (databaseStarted) {
//            System.out.println("PostgreSQL database started successfully!");
//        } else {
//            System.out.println("Failed to connect to PostgreSQL database after several attempts.");
//            return;
//        }
//
//
//    }
}
